version: '3.3'

services:
  db:
    build: ./mysql/   # Aplica o Build durante a execuçao do Docker compose
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
  
  flask:
    depends_on: 
      - db
    build: ./flask/ # Aplica o Build durante a execuçao do Docker compose
    ports:
      - "5000:5000"
    restart: always
    volumes:
      # Bindfo Mount: Diretório do projeto incluindo o /app do WORKDIR do dockerfile.
      - "/home/vitor/Documents/Worspace_Docker/Projeto5_Compose/6_bind_mount_compose/flask:/app"
    networks: 
      - dockercompose

networks:
  dockercompose: