version: '3.3' #Define a versão do Docker compose a ser utilizada (Comando do Compose)

services: #Servicos da aplicacao (Comando do Compose)

  db: #Container de MySQL
    image: mysql:5.7 #FROM mysql: 5.7
    volumes: #Lista de Volumes
      - db_data:/var/lib/mysql
    restart: always #Todas as alterações anteriores ao comando serão automaticamente atualizadas no Projeto
    env_file: # Carrega os parâmtros necessários de acesso através do caminh informado.
      - ./config/db.env
    networks: #Definindo a rede de conexão do container.
      - backend
      

  wordpress: #Configuração de outro serviço, que no caso é o Wordpress
    depends_on: #Determina outro serviço na qual esse serviço depende para excução, no caso depende do serviço "db" configurado anteriormente.
      - db
    image: wordpress:latest #Imagem base a ser utilizada no serviço pegando sempre a última versão. 
    ports:
    - "8000:80" #Porta 8000 da máquina e 80 do arquivo de configuração
    restart: always
    env_file: # Carrega os parâmtros necessários de acesso através do caminh informado.
      - ./config/wp.env
    networks: #Definindo a rede de conexão do container.
      - backend

volumes: #Chave de volumes criadas pois é obrigado a declarar todos os volumes da aplicação.
  db_data: {}
networks: # Declarando a rede no nível hierárquico máximo, onde vamos "dizer" pro Docker compose em qual rede deve se conectar
  backend:
    driver: bridge